### ISSUE TITLE
FEATURE REQUEST: Add a new flakes configuration which use home-manager as a nixosModules

### ISSUE THREAD

**Issue by Lewdovico** [Misterio77/nix-starter-configs#20]

**Comment by Misterio77** [comment]
Thanks. I'll get to it asap

**Comment by Misterio77** [comment]
I think I prefer to document it instead of add a new template (too much repetition bothers me a bit), so here's it: https://github.com/Misterio77/nix-starter-configs#use-home-manager-as-a-nixos-module

Closing this for now, but feel free to reopen if you think an additional template makes more sense!
