### ISSUE TITLE
Question about how imports work with home-manager for this setup

### ISSUE THREAD

**Issue by leighgable** [Misterio77/nix-starter-configs#23]
Hello Gabriel,
Thanks again for this repo. I'm running NixOS now thanks to you. 

I've run into a little problem while configuring Helix for language servers, etc.  I created a "programs" directory in the "home-manager" directory with a default.nix file in it, and then a helix sub-directory, and then added ```imports = [ ./programs  ];``` to the home.nix file. I then went too far for my level of understanding, and tried also adding your nix-colors package through the flake.nix file, and also referencing it in the imports of the home.nix file. I got an error stating, ``` ./programs does not look like a module.``` I then removed the reference to nix-colors, modified the import statement to: ```imports = import ./programs;``` which works fine, but now I don't have nix-colors, of course. 

My question is whether I am doing this all wrong for the architecture you've set up. Should I be putting my helix config and theme files in "modules/home-manager"? And if I do that what would the include look like in the home.nix file? Does it magically recognize modules, or would I need to reference a path? 

I know you're busy so no rush, no hard feelings if you don't have time...
All the best,
Leigh

**Comment by Misterio77** [comment]
Okay, so, suppose you have the following directory structure:
```
| home-config
  | config.nix
  | programs
    | helix
      | default.nix
```
and want to import `programs/helix/default.nix` into your `config.nix` file.

The simplest way is, at your `config.nix`:
```nix
{
  imports = [ ./programs/helix ]; # default.nix is used if the last component is a directory.
  # ...
}
```

If you instead use:
```nix
{
  imports = [ ./programs ];
}
```

Then it means it will try to import `./programs/default.nix`, and this file does not exist! For that, create it and add:
```nix
{
  imports = [ ./helix ];
}
```

Done! Now importing `./programs` should work.

---

Here's an explanation:

Basically, if you want to "concatenate" modules (home-manager or nixos configuration files) together, you'll use the _attribute_ `imports`. This is because the module system works that way. The modules are composed of `imports`, `options`, and `config` (more info [here](https://nixos.wiki/wiki/NixOS_modules)). Options are how you _create_ attributes you can set (so, create an abstraction) and config is when you _set options_ to a value (implementation). When creating your personal configuration, you usually are just setting `config`, so if you're not declaring `options` you can set the `config` at the top level. So, these are equivalent:

```nix
{ pkgs, ... }:
{
  imports = [ ./other/file.nix ];
  options = { };
  config = {
    environment.systemPackages = [ pkgs.neovim ];
  };
}
```

```nix
{ pkgs, ... }:
{
  imports = [ ./other/file.nix ];
  environment.systemPackages = [ pkgs.neovim ];
}
```

So, `imports` is how you combine different modules together. What about `import`?

`import` is a builtin _function_ that basically is replaced with the value from the file you're importing. That means the imported file does not need to be a module file, it can be any arbitrary nix expression.

For example, suppose you have this module on your config:
```nix
{ pkgs, ... }:
{
  environment.systemPackages = (import ./system-packages.nix) { inherit pkgs; };
}
```
`system-packages.nix`:
```nix
{ pkgs, ... }: [ pkgs.neovim ]
```

Noticed how I had to explicitly call a function and pass `pkgs` to it? And how `neovim.nix` is a function that returns an list? You can surely use `import` to modularize your configuration, and it affords a lot of flexibility (for example, you can have a file for functions you reuse!), but when combining modules it's almost always better to use `imports` instead.

**Comment by Misterio77** [comment]
> My question is whether I am doing this all wrong for the architecture you've set up. Should I be putting my helix config and theme files in "modules/home-manager"? And if I do that what would the include look like in the home.nix file? Does it magically recognize modules, or would I need to reference a path?

You're almost there! The right place to put it would be together with your home configuration. The idea of the `modules` directory is to place there modules that have actual `options`, that is, not your personal configurations, but abstractions other people would be interested to use! Like something you would upstream to home-manager.

**Comment by leighgable** [comment]
Wow! Thanks so much for the explanation.
