### ISSUE TITLE
Failing to build own packages in the standard

### ISSUE THREAD

**Issue by Alfrheim** [Misterio77/nix-starter-configs#71]
I have my own flake and want to add a new package.
I was trying to adapt my flake with some of your configurations and couldn't make the pkgs/default.nix work. 
Seems that the flake.nix is calling it with system instead of {inherit pkgs}.
I found the solution looking at you own nixos configuration.

So, I'm not sure if it's for my own flake or that maybe something changed and the template needs to be changed.

Thanks for making it public!

**Comment by Shensen1** [comment]
Can you link the fix pls?

**Comment by Edgaras1** [comment]
> Can you link the fix pls?

See https://github.com/Misterio77/nix-starter-configs/issues/54

**Comment by Alfrheim** [comment]
https://github.com/Misterio77/nix-starter-configs/blob/972935c1b35d8b92476e26b0e63a044d191d49c3/standard/flake.nix#L45

Here is where the system is passed.


In nix-config is like this:

https://github.com/Misterio77/nix-config/blob/705976cada91cfe64c479db8e498db46ba21a3e8/flake.nix#L123

Also the pkgs/default.nix is different:

https://github.com/Misterio77/nix-config/blob/705976cada91cfe64c479db8e498db46ba21a3e8/pkgs/default.nix#L1

**Comment by Misterio77** [comment]
Fixed in bb8a72b8e0e25f6a0ceb3574942a54cffe006cb9!

**Comment by Misterio77** [comment]
A quick explanation on the differences between `pkgs:` and `{pkgs ? import <nixpkgs> {}}`:

The former has to be called passing `pkgs` (e.g. `nixpkgs.legacyPackages.${system}`) as the single argument, while the latter is to be passed inside an attrset where it has the name `pkgs` (e.g. `{ pkgs = nixpkgs.legacyPackages.${system}; }`.

The latter's advantage is that you can expand it with optional arguments without breaking where it's called, and you can provide fallback values (such as `import <nixpkgs> { }`, which uses channels/nix_path).

Otherwise, it's just a style choice; I went with the former in the template as it's easier to grok.
